### ISSUE TITLE
postgres: could not serialize access due to concurrent update

### ISSUE THREAD

**Issue by mshorey** [unmade/shelf-showcase#3]
Cloned the git.  Everything seems to start up correctly but I get an error in the edgedb:
edgedb_1        | ERROR 43 2022-11-10T07:09:00.459 postgres: could not serialize access due to concurrent update

When trying to login with the default credentials I just get "Server error Something went wrong".

As everything else looks to be happy I have to assume it has to do with the edgedb error?  I tried on my two different docker machines and I get the same result.

**Comment by mshorey** [comment]
This was a red herring.  I was able to get things working by changing the API_BASE_URL from localhost to the LAN IP of my docker host and the CORS_ALLOW_ORIGINS from localhost to the LAN IP of my docker host.

**Comment by unmade** [comment]
Aw, the error was indeed confusing. Glad you found a solution! 
I'll make `CORS_ALLOW_ORIGINS` less strict, and add a note about changing API_BASE_URL accordingly
