### ISSUE TITLE
Open questions

### ISSUE THREAD

**Issue by fluckx** [unmade/shelf-showcase#7]
Heya,

Product looks pretty sleek and after some initial hickups I managed to get it working!

- Is there a way to turn off the register link at the bottom? If I'm publically hosting it for private use I'd rather not have every random person in the world sign up and dump god knows what in there!
- The add user button isn't working. Is that a placeholder?
- Any plans to add SSO integrations for user management? 

Looks pretty neat otherwise!

**Comment by unmade** [comment]
Hey, @fluckx 

Thanks for checking it out! And don't forget to check out the latest version - it is now has Dark Mode!

Could you tell me what were that initial hickups? Is it something that can be improved with documentation?

> Is there a way to turn off the register link at the bottom?

Great question! There is no way to disable it in a user-friendly way. I think this is something I should add. 

As a workaround, you can modify shelf-front (remove the whole `div` [here](https://github.com/unmade/shelf-front/blob/d32e724c35cb6e55cc7767c48aefae50408eed9b/src/pages/SignIn/index.jsx#L29)) and shelf-back (just remove [that](https://github.com/unmade/shelf-back/blob/cea377ce6af5371795ef6f599ad922dd7f178ae9/app/api/auth/views.py#L36) single line) source code and rebuild it. 

> The add user button isn't working. Is that a placeholder?

Yep, it's a placeholder. I removed it in the latest build, so it doesn't confuse anyone. This is something I've started working on, but then decided it was too soon to implement.

> Any plans to add SSO integrations for user management?

In a long term, yes. In a short-term, I don't think I will have enough time to add it. Any good examples with SSO that I should look at?

**Comment by fluckx** [comment]
> Could you tell me what were that initial hickups? Is it something that can be improved with documentation?
Mostly fuckups on my end when configuring caddy/the ports to have it behind SSL.
I exposed the docker containers on different ports, but did it wrong.

Looking forward to seeing some changes to the user management as well. I accidentally created a user and ditched the whole edgedb volume ( I hadn't done anything yet ).

Fingers crossed this project gets some traction.  I'll see if I can find some time to pitch in, but I haven't coded the past few years so I am quite a bit outdated!

**Comment by unmade** [comment]
@fluckx 
you can disable sign up by setting `FEATURES_SIGN_UP_DISABLED` to true in the .shelf-back.env

**Comment by fluckx** [comment]
Sweet! Thanks!
I'll check that out when I have a spare moment!
